[package]
version = "1.0.0" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Example Python Extension: Hello World"
description = "Demonstrates how to create a Python module that will startup / shutdown along with the extension."
category = "Example"
keywords = ["example"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["Anton Novoselov <anovoselov@nvidia.com>", "David Bosnich <dbosnich@nvidia.com>"]
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template-cpp"

# Define the Python modules that this extension provides.
[[python.module]]
name = "omni.example.python.hello_world"

# Define the documentation that will be generated for this extension.
[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
