[package]
version = "1.0.1" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Example C++ Extension: UI Widget"
description = "Demonstrates how to create a C++ widget for omni.ui"
category = "Example"
keywords = ["example", "C++", "cpp", "UI"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["Victor Yudin <vyudin@nvidia.com>", "David Bosnich <dbosnich@nvidia.com>"]
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template-cpp"

[dependencies]
"omni.ui" = {}

[[python.module]]
name = "omni.example.cpp.ui_widget"

[[native.library]]
path = "bin/${lib_prefix}omni.example.cpp.ui_widget${lib_ext}"

[[test]]
dependencies = [
    "omni.kit.renderer.capture",
    "omni.kit.ui_test",
]

args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]

stdoutFailPatterns.exclude = [
    "*omniclient: Initialization failed*",
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
cpp_api = [
     "include/CppWidget.h",
]
