[package]
version = "1.0.1" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Example C++ Extension: USDRT"
description = "Demonstrates how to create a C++ plugin that can interact with the current USDRT stage."
category = "Example"
keywords = ["example", "C++", "cpp", "fabric", "usdrt", "runtime"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["Jessica Jamieson <jjamieson@nvidia.com>"]
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template-cpp"

[dependencies]
"omni.kit.uiapp" = {}
"usdrt.scenegraph" = {}
"omni.kit.primitive.mesh" = {}

# Define the Python modules that this extension provides.
# C++ only extensions need this just so tests don't fail.
[[python.module]]
name = "omni.example.cpp.usdrt"

[[test]]
waiver = "Just example code, not for production"

# Define the C++ plugins that this extension provides.
[[native.plugin]]
path = "bin/*.plugin"

# Define the documentation that will be generated for this extension.
[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
cpp_api = [
     "include/omni/example/cpp/usdrt/IExampleUsdrtInterface.h",
]
