[package]
version = "1.0.0" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Example Python Extension: UI"
description = "Demonstrates how to create simple UI elements (eg. buttons and labels) from Python."
category = "Example"
keywords = ["example"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["Anton Novoselov <anovoselov@nvidia.com>", "David Bosnich <dbosnich@nvidia.com>"]
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template-cpp"

# List all dependencies of this extension.
[dependencies]
"omni.kit.uiapp" = {}
"omni.example.cpp.ui_widget" = {} # To demonstrate using widgets defined in C++

# Define the Python modules that this extension provides.
[[python.module]]
name = "omni.example.python.ui"

# Define any test specific properties of this extension.
[[test]]
dependencies = [
    "omni.kit.ui_test"
]

# Define the documentation that will be generated for this extension.
[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
